### ISSUE TITLE
template data option

### ISSUE THREAD

**Issue by burt202** [jaylinski/swig-webpack-plugin#2]
Hi, thanks for the plugin. Is there any chance you could add a "data" option, where its contents are made available to the template without nesting? At the moment I'm having to do

webpack.config.js

```
  plugins: [
    new SwigWebpackPlugin({
      template: "./public/templates/about.html",
      filename: "about.html",
      pageName: "about"
    })
  ]
```

about.html

```
<body class="{{ swigWebpackPlugin.options.pageName }}">
```

It would be nice to be able to do

webpack.config.js

```
  plugins: [
    new SwigWebpackPlugin({
      template: "./public/templates/about.html",
      filename: "about.html",
      data: {
        pageName: "about"
      }
    })
  ]
```

about.html

```
<body class="{{ pageName }}">
```

What do you think? Cheers

**Comment by jaylinski** [comment]
hi! would make sense, I'll have a look at it tomorrow.

**Comment by jaylinski** [comment]
@burt202 check out version 0.5.0. you should be able to access your data with

```
<body class="{{ data.pageName }}">
```

as stated in the readme

**Comment by burt202** [comment]
Cheers for the quick turnaround. Much appreciated
