### ISSUE TITLE
hello，some advice for swig-webpack-plugin

### ISSUE THREAD

**Issue by ciwyaitd** [jaylinski/swig-webpack-plugin#3]
ur works is so awesome.it's a very useful plugin for me. n thank you very much.(_^__^_) 
but when i want to put my html (not templateContent) to a new directory ,i havent find a way to do this.
n filename is not useful for it.
so i changed ur code @index.js line-64 , function emitHtml  last arguments add src or path before path.basename(template),so u need to add an option on the plugin.
n that will resolve my question.
u think it works?
my english is so bad.ahahah
nice to talk to u.
have a good day.
looking forward to ur reply.

**Comment by jaylinski** [comment]
hi @ciwyaitd , thanks for your input.
you are right, it would be nice to be able to overwrite the path-value from webpack-config with a custom path.
I'm open for pull requests. :)
